name: mottu_marvel
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  http: ^0.13.5
  localstorage: ^4.0.1+2
  firebase_core: ^2.10.0
  firebase_crashlytics: ^3.1.2
  crypto: ^3.0.2
  firebase_remote_config: ^4.0.2
  firebase_analytics: ^10.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
